### ISSUE TITLE
ElGamal version

### ISSUE THREAD

**Issue by stanbar** [TNO-MPC/protocols.distributed_keygen#3]
Hello,
I'm looking for a distributed key generation for elGamal. I found your repo, but as far as I know it supports only Paillier.  Could you please give me some suggestions on the modifications I have to do in order to make your codebase work with elGamal?

**Comment by ThomasTNO** [comment]
Hi @stanbar, thanks for reaching out. We are currently working on an implementation of ElGamal (without distributed keys). This would be more along the lines of https://github.com/TNO-MPC/encryption_schemes.paillier.
For distributed ElGamal *A Threshold Cryptosystem without a Trusted Party* (https://link.springer.com/chapter/10.1007/3-540-46416-6_47) might provide a mathematical basis.

In terms of modifcations, you probably need to modify most (decryption, encryption, key generation).
